In [1]:
import pandas as pd

In [2]:
pd.DataFrame({'Yes': [50, 21], 'No': [131, 2]})

   Yes   No
0   50  131
1   21    2

In [4]:
pd.DataFrame({'Bob': ['I liked it.', 'It was awful.'], 'Sue': ['Pretty good.', 'Bland.']})

             Bob           Sue
0    I liked it.  Pretty good.
1  It was awful.        Bland.

In [2]:
pd.DataFrame({'Bob': ['I liked it.', 'It was awful.'], 
              'Sue': ['Pretty good.', 'Bland.']},
             index=['Product A', 'Product B'])

                     Bob           Sue
Product A    I liked it.  Pretty good.
Product B  It was awful.        Bland.

In [3]:
pd.Series([1, 2, 3, 4, 5])

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [4]:
pd.Series([30, 35, 40], index=['2015 Sales', '2016 Sales', '2017 Sales'], name='Product A')

2015 Sales    30
2016 Sales    35
2017 Sales    40
Name: Product A, dtype: int64

In [6]:
ingredients = pd.Series(['4 cups', '1 cup', '2 large', '1 can'],
                         index=['Flour', 'Milk', 'Eggs', 'Spam'],
                         name='Dinner')

ingredients

Flour     4 cups
Milk       1 cup
Eggs     2 large
Spam       1 can
Name: Dinner, dtype: str

In [9]:
reviews = pd.read_csv("../input/wine-reviews/winemag-data_first150k.csv", index_col=0)

FileNotFoundError: [Errno 2] No such file or directory: '../input/wine-reviews/winemag-data_first150k.csv'

In [3]:
fruits = pd.DataFrame({'name': ['apple', 'banana', 'mango'],
                        'price': [1, 2, 3]})

#      name    price
#  0   apple   1
#  1   banana  2
#  2   mango   3

In [4]:
fruits.name       # dot style, like reading a property
fruits['name']    # bracket style, like a dictionary

0     apple
1    banana
2     mango
Name: name, dtype: str

In [5]:
fruits.iloc[0]       # the whole 1st row (apple)
fruits.iloc[:, 0]     # the whole 1st column (name) -- the ":" means "all rows"
fruits.iloc[0:2]      # 1st and 2nd rows only (apple, banana) -- stop is excluded, same as list slicing you already know

     name  price
0   apple      1
1  banana      2

In [6]:
fruits.loc[0, 'name']   # row labeled 0, column named 'name' -> 'apple'

'apple'

In [7]:
     name    price
0    apple   1
1    banana  2
2    mango   3

IndentationError: unexpected indent (1040181256.py, line 1)

In [8]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("zynicide/wine-reviews")

print("Path to dataset files:", path)

ModuleNotFoundError: No module named 'kagglehub'

In [3]:
fruits.loc[0, 'name']   # row labeled 0, column named 'name' -> 'apple'

NameError: name 'fruits' is not defined

In [2]:
pd.DataFrame({'Bob': ['I liked it.', 'It was awful.'], 
              'Sue': ['Pretty good.', 'Bland.']},
             index=['Product A', 'Product B'])

                     Bob           Sue
Product A    I liked it.  Pretty good.
Product B  It was awful.        Bland.